### ISSUE TITLE
Tests from upstream are 6 years old

### ISSUE THREAD

**Issue by kikofernandez** [for-GET/jesse#107]
Hi, when checking the testing from upstream (from `test/JSON-Schema-Test-Suite/`), I noticed that the tests that I think are used now are from 6 years ago, since the submodule commit has not changed. 

Is this the case? Thanks.

**Comment by seriyps** [comment]
Hi. It could easily be like that, yep. I guess, since JSON schema draft-04 have been released in 2013, there were no real need to update the test suites.

Now, if we get the draft-06 merged, I think it would make a lot of sense to update the test suites as well eventually.

**Comment by andreineculau** [comment]
to be fixed in #108
