### ISSUE TITLE
Default schema loader fun with file and http/s support

### ISSUE THREAD

**Issue by andreineculau** [for-GET/jesse#23]
I don't know if this is legacy (jesse not supporting $ref in the beginning) but i have a commit that adds loading (and adding to internal storage) referenced schemas given a start schema with an id using the file: or http: URI scheme.

This works brilliantly for the CLI version.

Ping @Cy6erBr4in

**Comment by andreineculau** [comment]
Correction: if this is legacy, or design that jesse lack this default behavior

**Comment by dmitriid** [comment]
IIRC it was by design: the `$ref` was a bit of a mess standard-wise and not used within the company. So it was never implemented (though @Cy6erBr4in wanted to do it for a long time)

**Comment by andreineculau** [comment]
By all my standards, that's legacy 😀 
If you know what was messy about the standard, I'd appreciate a shout, because the $ref support is already in jesse.
Worked a bit on my future PR and I think it will close down all the 3 open issues actually. So if there's extra work, this is a good moment to tackle it.

Thanks for jumping in!

--
http://andreineculau.com

**Comment by andreineculau** [comment]
fixed by #24
