### ISSUE TITLE
Master add_schema broken

### ISSUE THREAD

**Issue by seanmcevoy** [for-GET/jesse#37]
Last night (8th jan 2017) we did a build which clones the jesse repo and we pulled the latest master branch, which seems to be broken. From a quick review the order of parameters from jesse:add_schema/2 (which we call) into jesse_database seem to be incorrect, though I'm judging by variable name only, with no knowledge of internal workings.
Last fridays (6th jan 2017) master version was working fine.

**Comment by andreineculau** [comment]
Can you try with the newest master? Thanks a bunch!

**Comment by seanmcevoy** [comment]
Still failing unfortunately, stopping in the dialyzer phase of the build with:

The call jesse:add_schema(MsgType::atom(),Json::any()) will never return since it differs in the 1st argument from the success typing arguments: (string(),any())

**Comment by andreineculau** [comment]
Hmm, I need to look into why travis doesn't catch this in the dialyzer run

**Comment by andreineculau** [comment]
@seanmcevoy try now. I blindly fixed the spec. Shame! I have no idea what's happening with dialyzer: nor on my computer, nor travis seems to catch the spec issue, and I don't have the time to look more into it. Thus I keep the issue open.

@sstrigler could you maybe lend a helping hand, and look into why 3a08f9b does not fail `make dialyzer` ?

**Comment by sstrigler** [comment]
You mean why it did not before the fix, right?

**Comment by sstrigler** [comment]
Now that I read everything again: where you instead asking why after https://github.com/for-GET/jesse/commit/3a08f9b0698b82c2078179a661fe4f7a2ba2bc9c dialyzer didn't fail?

**Comment by andreineculau** [comment]
@seanmcevoy now that I look closer, your dialyzer error stems from your own call right? and that's because the spec of `jesse_database:add_schema` did change from taking Key as an atom, to taking Key as a string. That said, in the current master, there should be little use of calling `add_schema` because jesse will automatically load schemas on demand, given that the `ref` property points to a an actual file on disk (I assume that's your current case). See #24 

@sstrigler thanks :)

**Comment by seanmcevoy** [comment]
@andreineculau that is indeed the case. I was under time pressure earlier just pasted in the dialyzer error without any investigation, after changing my key to an atom dialyzer has passed & the tests are passing again. We'd pointed our rebar.config to the last working version so it it wasn't a blocker for us.

Specifically, thanks for your quick reply & fix for this, and in general, thanks for the open source library! Much appreciated!

**Comment by andreineculau** [comment]
thanks must go to all authors and issue reporters
