### ISSUE TITLE
Errors returned are different depending on options used

### ISSUE THREAD

**Issue by eproxus** [for-GET/jesse#40]
With jesse 1.4.0, I'm having trouble using the options `[]` and `[{allowed_errors, 1}]`, because yields different results. For example, consider the following example document:

```json
{
    "data": {
        "type": "document",
        "id": 1
    }
}
```
where `/data/id` should be `"1"` and not `1` and the schema from http://jsonapi.org/schema

The problem is that using `[]` or `[{allowed_errors, 0}]` yields a different error than `[{allowed_errors, 1}]`. Because of that there is no single API call that would always yield the same error first (i.e. one has to first validate and get an error, then validate again with allowed errors set to `1` to get the specific error).

Maybe I'm misunderstanding how jesse operates, but for the above document and schema using `infinity` yields a lot of errors for all the branches of the schema (although the document is correct). 

Is there a canonical way to validate the document successfully (because it *is* valid) and get the most specific error first?

### Expected

Using `[{allowed_errors, 1}]` we get:

```erlang
34> jesse:validate(jsonapi, #{<<"data">> => #{<<"type">> => <<"user">>, <<"id">> => 1}}).
{error,[{data_invalid,#{<<"type">> => <<"string">>},
                      wrong_type,1,
                      [<<"data">>,<<"id">>]}]}
```

### Actual

Using no options, we get `not_one_schema_valid` as the first error, where one would expect the most specific error first (as with allowing only 1 error).

```erlang
1> jesse:validate(jsonapi, #{<<"data">> => #{<<"type">> => <<"user">>, <<"id">> => 1}}).
{error,[{data_invalid,#{...schema redacted...},
                      not_one_schema_valid,
                      #{<<"data">> => #{<<"id">> => 1,<<"type">> => <<"user">>}},
                      []}]}
```

**Comment by andreineculau** [comment]
@eproxus apologies for the 1y silence. AFAICS I cannot reproduce this with the current master.

```
7> jesse:validate_with_schema(#{<<"$schema">> => <<"http://json-schema.org/draft-03/schema#">>, <<"type">> => <<"object">>, <<"properties">> => #{<<"id">> => #{<<"type">> => <<"string">>}}}, #{<<"id">> => 1}, [{allowed_errors,1}]).
{error,[{data_invalid,#{<<"type">> => <<"string">>},
                      wrong_type,1,
                      [<<"id">>]}]}
8> jesse:validate_with_schema(#{<<"$schema">> => <<"http://json-schema.org/draft-03/schema#">>, <<"type">> => <<"object">>, <<"properties">> => #{<<"id">> => #{<<"type">> => <<"string">>}}}, #{<<"id">> => 1}, [{allowed_errors,0}]).
{error,[{data_invalid,#{<<"type">> => <<"string">>},
                      wrong_type,1,
                      [<<"id">>]}]}
9> jesse:validate_with_schema(#{<<"$schema">> => <<"http://json-schema.org/draft-03/schema#">>, <<"type">> => <<"object">>, <<"properties">> => #{<<"id">> => #{<<"type">> => <<"string">>}}}, #{<<"id">> => 1}, [{allowed_errors,infinity}]).
{error,[{data_invalid,#{<<"type">> => <<"string">>},
                      wrong_type,1,
                      [<<"id">>]}]}
10> jesse:validate_with_schema(#{<<"$schema">> => <<"http://json-schema.org/draft-03/schema#">>, <<"type">> => <<"object">>, <<"properties">> => #{<<"id">> => #{<<"type">> => <<"string">>}}}, #{<<"id">> => 1}, []).                        {error,[{data_invalid,#{<<"type">> => <<"string">>},
                      wrong_type,1,
                      [<<"id">>]}]}
```

Please tell me if you're still having issues and I'll follow up on them.

**Comment by eproxus** [comment]
@andreineculau No worries 🙂 We're not working on this project at the moment, but trying it out as described in my original report, I no longer see the `not_one_schema_valid` error anymore.
