### ISSUE TITLE
"required" has no effect

### ISSUE THREAD

**Issue by subsetpark** [for-GET/jesse#58]
I am dynamically generating some JSON validation, but certain properties are not being validated against. Here's an example:

```erl
    Candidates = Election#election.candidates,
    Validation = {[{<<"type">>, <<"object">>},
                   {<<"properties">>,
                    {[{Candidate, {[{<<"type">>, <<"integer">>}]}} || Candidate <- Candidates]}},
                   {<<"required">>, Candidates},
                   {<<"additionalProperties">>, false}
                  ]},
    io:fwrite("Schema: ~s~n", [jiffy:encode(Validation)]),
    io:fwrite("~p~n", [Validation]),
    jesse:validate_with_schema(Validation, jiffy:decode(Body)).
```

And here's the output, along with a report of what was passed in if it passes validation:

```erl
Schema: {"type":"object","properties":{"x":{"type":"integer"},"y":{"type":"integer"},"z":{"type":"integer"}},"required":["x","y","z"],"additionalProperties":false}
{[{<<"type">>,<<"object">>},
  {<<"properties">>,
   {[{<<"x">>,{[{<<"type">>,<<"integer">>}]}},
     {<<"y">>,{[{<<"type">>,<<"integer">>}]}},
     {<<"z">>,{[{<<"type">>,<<"integer">>}]}}]}},
  {<<"required">>,[<<"x">>,<<"y">>,<<"z">>]},
  {<<"additionalProperties">>,false}]}
Passed validation: {[{<<"x">>,1}]}
Passed validation: {"x":1}
```

As you can see, when an object containing only one of the three required properties is passed in, it passes validation.

On the other hand, if I pass in `{"i":1}`, the validation fails according to the `additionalProperties` constraint.

Can you let me know what i'm doing wrong?

**Comment by andreineculau** [comment]
the "problem" is that you do not specify which schema validation to use, and by default `jesse` use draft3 which has a different way to saying which properties are required or optional.

So add `"$schema": "http://json-schema.org/draft-04/schema#"`, and you should be fine.

**Comment by subsetpark** [comment]
That clears it up. Thank you for your advice!
