### ISSUE TITLE
allow non-schema keys alongside $ref

### ISSUE THREAD

**Issue by fenollp** [for-GET/jesse#62]
Since 1.5.0 or rather #54 this schema fails:
```json
{
  "refs": {
    "not": {
      "type": "null"
    }
  },
  "$ref": "#refs/A"
}
```
with `only_ref_allowed`. Not sure how correct the implementation of https://www.jsonschemavalidator.net is but it says this is a valid draft04 schema.

Side note: I believe jesse's handling of `not` schemas is incorrect but I'll investigate more on that.

**Comment by fenollp** [comment]
Side note update: `not`s are not in draft04.
Updated example code:
```json
{
  "A": {
    "type": "null"
  },
  "$ref": "#/A"
}
```
```erlang
jesse:validate_with_schema(#{<<"A">> => #{<<"type">> => <<"null">>}, <<"$ref">> => <<"#/A">>}, null, [{allowed_errors, infinity}, {default_schema_ver, <<"http://json-schema.org/draft-03/schema#">>}])
```
```erlang
{error,[{schema_invalid,#{<<"$ref">> => <<"#/A">>,
                          <<"A">> => #{<<"type">> => <<"null">>}},
                        only_ref_allowed}]}
```

**Comment by andreineculau** [comment]
From http://json-schema.org/latest/json-schema-core.html#rfc.section.7

> Resolved against the current URI base, it identifies the URI of a schema to use. All other properties in a "$ref" object MUST be ignored.

**Comment by fenollp** [comment]
Your link should be pointing to section 8.3 instead of 7. 

While I understand that you could dismiss this issue from an interpretation of 8.3, I believe there is room here. In my simplified example above `"A"` counts as a definition, not a schema constraint as items, properties or type are.
More than one other implementation take that same stance: only the constraints from $ref MUST be respected, all other keys MUST be ignored. 
I really think erroring on this schema is a misinterpretation and that 1.5.0 should go back to behaving as it did in 1.5.0-rc2 and before with regards to this issue. 
Also, how else can you express that schema while using a ref?

**Comment by fenollp** [comment]
Ah yes my sample is purposefully contrived: I wanted to say that you should be able to use a $ref at the root level of a schema. 

I stand by my point that “A” is not encompassed by “all other properties of a $ref object”: “A” is not a property it’s a definition. 

I don’t know who’s right. I believe there is room for interpretation in that § and that at least the lib behind https://www.jsonschemavalidator.net considers that sample valid. Let’s see :)
