### ISSUE TITLE
Need some advise for a new JSON schema validator

### ISSUE THREAD

**Issue by expelledboy** [for-GET/jesse#68]
I am the developer of [ejsv](https://github.com/patternmatched/ejsv). I needed a JSON schema validation library that could easily be extended and shared logic where possible, and I read through Jesse and found it very difficult in that regard.  I am not familar with JSON schema, but I like my Erlang work 🤣 

So I managed to achieve the requirement by implementing an abstraction between the keyword rules and the assertions themselves, but I failed to think about $ref's 💩 

I was thinking I needed a more fine grained API in `ejsv_cache`, what might you recommend? The code is quite simple to read through (I hope) and I would really appreciate your thoughts otherwise!

**Comment by andreineculau** [comment]
I'm sorry but I really don't have the time for this (I'm on parental leave). It is also not a jesse issue, so I'm closing. Best of luck with ejsv, but as you know jesse also has a tracking issue to be more extensible, and support newer drafts https://github.com/for-GET/jesse/issues/61

**Comment by expelledboy** [comment]
No worries, congrats!
