### ISSUE TITLE
jesse:load_schema/2 question

### ISSUE THREAD

**Issue by mrallen1** [for-GET/jesse#78]
I have my schemas in `priv/schema` which I am loading by

```erlang
Path = code:application(foo) ++ "/schema",
jesse:load_schemas(Path, fun(D) -> jiffy:decode(D, [return_maps]) end).
```

Later, I want to reference these loaded schemas by the ids embedded in the schemas themselves, but it appears the only way they're stored is using absolute paths on my local disk.

Example:
```json
{
  "$id": "http://example.com/schema/foo.json",
}
```

Later I want to

```erlang
jesse:validate("http://example.com/schema/foo.json", InputJSON)
```

but of course it says there's no schema named that. It seems like jesse attempts to locate the id attribute in a schema - does it just ignore it?

**Comment by f3c0** [comment]
I think jesse uses use "id" instead of "$id"
```
{
  "id": "http://example.com/schema/foo.json",
}
```

**Comment by mrallen1** [comment]
Yes, that's right. Thanks for the answer
