### ISSUE TITLE
oneOf doesn't fail when nested in a list?

### ISSUE THREAD

**Issue by mrallen1** [for-GET/jesse#82]
```
Schema = jiffy:decode(F, [return_maps]).                                                                       
#{<<"additionalProperties">> => false,
  <<"minProperties">> => 1,
  <<"patternProperties">> =>
      #{<<"^[a-zA-Z]{1}[a-zA-Z0-9_]{2,}$">> =>
            #{<<"oneOf">> =>
                  [#{<<"type">> => <<"number">>},
                   #{<<"type">> => <<"string">>},
                   #{<<"type">> => <<"boolean">>},
                   #{<<"type">> => <<"null">>},
                   #{<<"items">> =>
                         #{<<"oneOf">> =>
                               [#{<<"type">> => <<"number">>},
                                #{<<"type">> => <<"string">>},
                                #{<<"type">> => <<"boolean">>}]},
                     <<"type">> => <<"array">>}]}}}
27> Body1 = #{ <<"key1">> => 9, <<"albatross">> => <<"value1">>, <<"list">> => [true, 1, [<<"something">>, null]]}.
#{<<"albatross">> => <<"value1">>,<<"key1">> => 9,
  <<"list">> => [true,1,[<<"something">>,null]]}

```

Expected result: a list value with a list inside of it should fail `oneOf` validation as defined above.

Actual result:
```
28> jesse:validate_with_schema(Schema, Body1).                                                                     
{ok,#{<<"albatross">> => <<"value1">>,<<"key1">> => 9,
      <<"list">> => [true,1,[<<"something">>,null]]}}
```
I don't understand why?

**Comment by mrallen1** [comment]
It's because the default validator seems to be `schema-03`. When I explicitly turn on `schema-04` it works.

**Comment by seriyps** [comment]
Yeah, looks strange. Could this example be further reduced to minimal one
to reproduce?

пн, 15 июл. 2019 г., 22:31 Mark Allen <notifications@github.com>:

**Comment by andreineculau** [comment]
Works as expected afaik. I'm cannot check myself right now but v3 doesn't have a definition for oneOf, allOf, etc Might even be that v3 and earlier expect singular "item", not plural "items". So at least 1, but maybe even 2 rules are ignored. It didn't occur to me until now but maybe it's useful to return the schema paths that are ignored.

**Comment by seriyps** [comment]
Ah, sorry, true.

> It didn't occur to me until now but maybe it's useful to return the schema paths that are ignored.

Sounds useful. Can actually be a separate function to just feed it with schema and it will return a list of rules it doesn't know? Because the list of rules that are ignored doesn't depend on data, only schema.

**Comment by mrallen1** [comment]
I figured out my issue :) Thanks
