### ISSUE TITLE
Tagged release

### ISSUE THREAD

**Issue by tjarvstrand** [for-GET/jesse#9]
Hey,

We are updating jesse internally and would like to use upstream version numbers. Any chance we could get a tagged release of the current version?

**Comment by andreineculau** [comment]
Sure. I had a few things on standby, so I was stalling. Coming in 5min

**Comment by andreineculau** [comment]
https://github.com/for-GET/jesse/releases/tag/1.2.0

**Comment by tjarvstrand** [comment]
Thanks!
