### ISSUE TITLE
Move from Travis CI to GitHub Actions?

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [for-GET/jesse#97]
Would you be interested in a pull request that moves CI from Travis CI to GitHub Actions, or at least adds GitHub Actions alongside Travis CI? It seems travis-ci.org will stop being useful from Dec 31 2020. I can do it, except that I think you need to create the workflow yml, first, in `master`, after which I can branch off of.

**Comment by andreineculau** [comment]
Hej Paulo. Yes, I've also started moving all projects over to GitHub as well. Travis put the nail on the coffin that everyone saw coming 2y so. There are a few alternatives on the table on how to move forward. I'll get back to you shortly. Thanks for poking👏

--
http://andreineculau.com

**Comment by paulo-ferraz-oliveira** [comment]
I'll create a PR, in the meantime (since it's really easy to adopt GitHub Actions) and then we can iterate on it, or close it, if you think a better alternative is in order.
